; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

;#define MyAppName "Liger"
;#define MyAppVersion "1.1.0"
;#define MyAppPublisher "The University of Sheffield"
;#define MyAppURL "https://github.com/ligerdev/liger"
;#define MyAppExeName "liger.exe"

;#define ProjectDir "C:\Users\steve\Documents\SmartGit_Repos\liger"
;#define BuildDir "C:\Users\steve\Documents\SmartGit_Repos\Liger_6_0_0_Installation"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9F1544F8-D20C-4975-88FE-3AA3D706909D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonpf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile={#ProjectDir}\LICENSE
OutputDir={#BuildDir}
OutputBaseFilename=liger-win-{#MyAppVersion}-x64
Compression=lzma
SolidCompression=yes
ChangesEnvironment=true
UninstallDisplayIcon={app}\{#MyAppExeName}
ChangesAssociations=yes
; "ArchitecturesInstallIn64BitMode=x64" requests that the install be
; done in "64-bit mode" on x64, meaning it should use the native
; 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; 
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; 
Name: modifypath; Description: &Add MATLAB path to system path;

[Files]
Source: "{#BuildDir}\bin\liger.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "{#BuildDir}\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#BuildDir}\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#BuildDir}\share\*"; DestDir: "{app}\share"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#BuildDir}\bin\vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"
Name: "{group}\Uninstall"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{tmp}\vc_redist.x64.exe"; Check: VCRedistNeedsInstall; Flags: postinstall nowait skipifsilent

[Registry]
Root: HKCR; Subkey: ".lgr"; ValueType: string; ValueName: ""; ValueData: "LigerWorkflowFile"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "LigerWorkflowFile"; ValueType: string; ValueName: ""; ValueData: "Liger Workflow File"; Flags: uninsdeletekey
Root: HKCR; Subkey: "LigerWorkflowFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\bin\{#MyAppExeName},0"
Root: HKCR; Subkey: "LigerWorkflowFile\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\bin\{#MyAppExeName}"" ""%1"""

[Code]
const 
  ModPathName = 'modifypath';
  ModPathType = 'user';

function ModPathDir(): TArrayOfString;
var 
  MatlabRootFolder: String;
  MatlabInstalled: Boolean;
  psub1, psub2, psub3, Path1, Path2, Path3: String;
begin
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\8.1', 'MATLABROOT', MatlabRootFolder); // 2013a
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\8.2', 'MATLABROOT', MatlabRootFolder); // 2013b
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\8.3', 'MATLABROOT', MatlabRootFolder); // 2014a
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\8.4', 'MATLABROOT', MatlabRootFolder); // 2014b
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\8.5', 'MATLABROOT', MatlabRootFolder); // 2015a
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\8.6', 'MATLABROOT', MatlabRootFolder); // 2015b
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.0', 'MATLABROOT', MatlabRootFolder); // 2016a
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.1', 'MATLABROOT', MatlabRootFolder); // 2016b
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.2', 'MATLABROOT', MatlabRootFolder); // 2017a
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.3', 'MATLABROOT', MatlabRootFolder); // 2017b
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.4', 'MATLABROOT', MatlabRootFolder); // 2018a
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.5', 'MATLABROOT', MatlabRootFolder); // 2018b
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.6', 'MATLABROOT', MatlabRootFolder); // 2019a
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.7', 'MATLABROOT', MatlabRootFolder); // 2019b
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.8', 'MATLABROOT', MatlabRootFolder); // 2020a
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.9', 'MATLABROOT', MatlabRootFolder); // 2020b
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.10', 'MATLABROOT', MatlabRootFolder); // 2021a
  MatlabInstalled := RegQueryStringValue(HKLM, 'SOFTWARE\MathWorks\MATLAB\9.11', 'MATLABROOT', MatlabRootFolder); // 2021b
  if MatlabInstalled then
  begin
  
    // MsgBox('Found MATLAB Installation in ' + MatlabRootFolder, mbInformation, MB_OK);

    psub1 := '\extern\bin\win64';
	psub2 := '\runtime\win64';
	psub3 := '\bin';

	Path1 := MatlabRootFolder + psub1;
	Path2 := MatlabRootFolder + psub2;
	Path3 := MatlabRootFolder + psub3;

    setArrayLength(Result, 3);
	Result[0] := ExpandConstant(Path1);
	Result[1] := ExpandConstant(Path2);
	Result[2] := ExpandConstant(Path3);
  end
end;
#include "modpath.iss"

// Check if vcredist is installed
#IFDEF UNICODE
  #DEFINE AW "W"
#ELSE
  #DEFINE AW "A"
#ENDIF
type
  INSTALLSTATE = Longint;
const
  INSTALLSTATE_DEFAULT = 5;      // The product is installed for the current user.
  // Visual C++ 2019 Redistributable 14.25.28508
  VC_2019_REDIST_X64_MIN = '{EEA66967-97E2-4561-A999-5C22E3CDE428}';
  VC_2019_REDIST_X64_ADD = '{7D0B74C2-C3F8-4AF1-940F-CD79AB4B2DCE}';

function MsiQueryProductState(szProduct: string): INSTALLSTATE; 
  external 'MsiQueryProductState{#AW}@msi.dll stdcall';

function VCVersionInstalled(const ProductID: string): Boolean;
begin
  Result := MsiQueryProductState(ProductID) = INSTALLSTATE_DEFAULT;
end;

function VCRedistNeedsInstall: Boolean;
begin
  // here the Result must be True when you need to install your VCRedist
  // or False when you don't need to, so now it's upon you how you build
  // this statement, the following won't install your VC redist only when
  // the Visual C++ 2010 Redist (x86) and Visual C++ 2010 SP1 Redist(x86)
  // are installed for the current user
  Result := not (VCVersionInstalled(VC_2019_REDIST_X64_MIN) and 
    VCVersionInstalled(VC_2019_REDIST_X64_ADD));
end;
